### ISSUE TITLE
Level up music default value

### ISSUE THREAD

**Issue by Krysaczek** [maximonster/TaskJingle#8]
Level up music should probably be off by default. There's nothing wrong with the feature itself, but all active installs so far wanted task jingle only. It took me a while to find the source of the level up music and I have seen quite a lot of chatter about it.

**Comment by maximonster** [comment]
Fixed in latest commit thanks for letting me know

**Comment by dowodenum** [comment]
I finally found this today after getting annoyed enough to look into it. SoundSwapper debug wouldn't list it, so I had to go through my plugin list manually and consider/investigate each one. Since I already had it installed before your fix, it didn't change my setting back to the expected defaults.

It really should've just been a new plugin...

**Comment by maximonster** [comment]
Sorry for the inconvenience. You're right it should've been a separate plugin.
